### ISSUE TITLE
observers $lookup 

### ISSUE THREAD

**Issue by DeanKamali** [robfallows/tunguska-reactive-aggregate#33]
Hi Rob, 

I have noticed that aggregation doesn't re-run when there is a change in a referenced collection with ```$lookup ``` stage.

For example, if change happens in``` users``` collection aggregation doesn't re-run.  

is that by design?

```
Meteor.publish("appointments", function (Id) {
  ReactiveAggregate(
    this,
    Events, // Pipeline
    [
      {
        $lookup: {
          from: "users",
          let: {
            providerId: "$providerId"
          },
          pipeline: [
            {
              $match: {
                $expr: {
                  $eq: ["$$providerId", "$_id"]
                }
              }
            },
            {
              $project: {
                name: { $concat: ["$profile.name.first", " ", "$profile.name.last"] }
              }
            }
          ],
          as: "providerName"
        }
      }
    ],
    {
      clientCollection: "Appointments"
    }
  );
});
```

**Comment by robfallows** [comment]
That's the expected behaviour. If you provide no other options, the only collection which is observed for changes is the collection the aggregation is based from (`Events` in this example).

However, if you follow the example here: <https://github.com/robfallows/tunguska-reactive-aggregate#using-lookup>, you will be able to attach any number of dependent observers.

**Comment by DeanKamali** [comment]
That's great! Thank you so much for your help!
