### ISSUE TITLE
SimpleSchema not callable in 1.3.0, aggregate.js:128:16

### ISSUE THREAD

**Issue by JanMP** [robfallows/tunguska-reactive-aggregate#37]
After updating from 1.2.5 to 1.3.0, I get this error in all subscriptions using ReactiveAggregate (thanks btw, I use this a lot) 

```
Exception from sub IKs id hqGPBSMXtckQEexab TypeError: Right-hand side of 'instanceof' is not callable
 at ReactiveAggregate (packages/tunguska:reactive-aggregate/aggregate.js:128:16)
 at Subscription.<anonymous> (imports/api/Faelle.coffee:59:5)
...
```

**Comment by robfallows** [comment]
Hi @JanMP . Are you using `aldeed:simple-schema` or npm `simpl-schema` in your project?

**Comment by JanMP** [comment]
npm simpl-schema

**Comment by robfallows** [comment]
@RealHandy : Any thoughts?

**Comment by RealHandy** [comment]
@JanMP Do you have any circular references in your SimpleSchema, or circular import/require references in your code? I've found some info that suggests this error can happen in the case of a circular reference.

**Comment by JanMP** [comment]
I do have at least one circular reference in the schema of my main collection. 
But I haven't actually got around to attach any of my schemas to the collections. So I got collections2 and simple-schema but no schemas attached, yet (I use the scemas quite extensively to generate ui, e.g I got a react-component that builds ui to define complex mongo-queries for collections with nested subdocuments just from the schema).
I also have this error with some really simple collections.
I just checked if removing collections2 makes a difference, but it doesn't.

**Comment by RealHandy** [comment]
This is something I'm only just now learning because of the problem you're having, but there is a thing about the difference between require and import that can cause the error you're having IF you use requires rather than imports, and there is a circular package/module reference. aggregate.js must use a require in order to determine whether or not you have the simpl-schema package installed. I can't use an import or it will make simpl-schema a requirement instead of optional (imports are load-time vs run-time and just crash the program if you don't have the package).

Since you don't have schemas attached to collections, to me that suggests that the problem is a circular reference issue with packages/modules. There's also a related and possibly very relevant issue, that if you use CoffeeScript, it compiles to CommonJS, which will use requires and make this problem more likely. You are using CS, so that seems like a possibility. Can you remove any circular module references and test it again? That's probably a big pain. Can you share some code bits to show what your circular references are?

**Comment by JanMP** [comment]
I've been working full-time on that project since June and there are quite a few modules by now. Seems like there are some tools to help detect circular imports, but they require web pack. So I'd have to check for that manually. Without a testing tool, there's no way to determine if I succeeded in finding all circular imports - if there are any in the first place, wich is quite likely but who knows? I'll take a look, but I don't think I'll come up with results any time soon...

**Comment by RealHandy** [comment]
Try copying the tunguska-reactive-aggregate project into /packages/tunguska-reactive-aggregate in your project directory (this is the standard way to override packages with a local version for dev purposes. Then replace the aggregate.js file there with the unzipped attached one I've provided here. This file is modified to use import instead of require to load the package. If this works, then that'll at least confirm what the problem is.
[aggregate.zip](https://github.com/robfallows/tunguska-reactive-aggregate/files/4383469/aggregate.zip)

**Comment by JanMP** [comment]
Yes, this works.

**Comment by RealHandy** [comment]
Okay. So, this is apparently an issue with circular requires in your code. Very possibly due to your code being CoffeeScript, but maybe not -- I'm only getting that from reading about others' experiences with CS and circular references. However, I've found some interesting stuff about getting require() to have enough time to resolve circular dependencies. It seems as though this change might work -- download it and give it a try.
[aggregate.zip](https://github.com/robfallows/tunguska-reactive-aggregate/files/4389714/aggregate.zip)

**Comment by robfallows** [comment]
Awesome research @RealHandy 👍

**Comment by JanMP** [comment]
The new approach seems to work, too.

Btw, CS1 didn't support import statements and the meteor implementation patched that in translating those imports into requires (never understood why they bothered).
But CS2 does support import and the resulting js contains import statements. So I don't really see, why that should still be turned into require.

**Comment by RealHandy** [comment]
Thanks, @robfallows :)
Credit to @benjamn (no surprise) for this post from 2016 for setting me on the right path: https://github.com/meteor/meteor/issues/6381#issuecomment-193938592

I've created a PR to update to 1.3.1 for this fix.

@JanMP Yeah, it may not be CoffeeScript's js generation, it could just be the circular dependencies in general. When 1.3.1 is available, you can update to that and get rid of your local /packages testing version.
